/* ============================================================================
   PHOTO GALLERY CONTENT
   ----------------------------------------------------------------------------
   Generated by `node tools/rebuild-gallery.js`, but safe to edit by hand.

   HOW TO ADD PHOTOS
   1. Put your photos in a folder:  images/<YEAR>/<Album Name>/
   2. Either run the rebuild command above, or add an entry below to match.
   3. Write a description for the album in the `description` field.

   Descriptions are preserved when you re-run the rebuild command.
   Years are displayed newest-first automatically.
   ========================================================================== */

window.SITE_GALLERY = [
  {
    year: 2024,
    albums: [
      {
        title: "Albany Adventures",
        description: "A weekend upstate between rotations — long light, cold air, and the kind of quiet that only shows up when you finally stop moving.",
        layout: "justified",
        photos: [
          "images/2024/Albany Adventures/IMG_01.png",
          "images/2024/Albany Adventures/IMG_02.png"
        ]
      }
    ]
  },

  {
    year: 2023,
    albums: [
      {
        title: "Diploma & Drip",
        description: "Graduation season. Four years of coursework, one very good outfit, and the people who made it all survivable.",
        layout: "justified",
        photos: [
          "images/2023/Diploma & Drip/IMG_01.jpg",
          "images/2023/Diploma & Drip/IMG_02.jpg"
        ]
      }
    ]
  },

  {
    year: 2022,
    albums: [
      {
        title: "A’s Christmas Pawrty",
        description: "Warm rooms, low light, and everyone home at the same time for once — the good boy included.",
        layout: "justified",
        photos: [
          "images/2022/A’s Christmas Pawrty/IMG_01.jpg",
          "images/2022/A’s Christmas Pawrty/IMG_02.jpg",
          "images/2022/A’s Christmas Pawrty/IMG_03.jpg",
          "images/2022/A’s Christmas Pawrty/IMG_04.jpg"
        ]
      }
    ]
  },

  {
    year: 2021,
    albums: [
      {
        title: "A Walk Through Oregon",
        description: "Pacific Northwest green — tall trees, wet air, and a lot of walking with no particular destination in mind.",
        layout: "justified",
        photos: [
          "images/2021/A Walk Through Oregon/IMG_01.png",
          "images/2021/A Walk Through Oregon/IMG_02.png",
          "images/2021/A Walk Through Oregon/IMG_03.png",
          "images/2021/A Walk Through Oregon/IMG_04.png",
          "images/2021/A Walk Through Oregon/IMG_05.png",
          "images/2021/A Walk Through Oregon/IMG_06.png"
        ]
      },
      {
        title: "Oregon Shenanigans",
        description: "The other half of the same trip — less scenery, more of the people I was lucky enough to be there with.",
        layout: "justified",
        photos: [
          "images/2021/Oregon Shenanigans/IMG_01.png",
          "images/2021/Oregon Shenanigans/IMG_02.png",
          "images/2021/Oregon Shenanigans/IMG_03.png",
          "images/2021/Oregon Shenanigans/IMG_04.png"
        ]
      }
    ]
  }
];
